### ISSUE TITLE
📢Announcing: WinUI 3 in Windows App SDK 1.0 Preview 2 🎨💻

### ISSUE THREAD

**Issue by gabbybilka** [microsoft/microsoft-ui-xaml#6049]
We've just shipped the latest version of WinUI 3, which is a part of Windows App SDK 1.0 preview release! This release includes new features, bug fixes and provides access to APIs and features we are intending to include in the next stable release.  
 
## Shipping WinUI 3 as a part of the Windows App SDK
 
In order to use this version of WinUI 3, you'll download the **Windows App SDK (Preview)** Visual Studio Extension (VSIX) to get started. The Windows App SDK VSIX includes WinUI project templates that you'll use to build your WinUI 3 app, as well as access to other [Windows App SDK components](https://docs.microsoft.com/windows/apps/windows-app-sdk/release-channels#features-available-by-release-channel). The Windows App SDK package includes a reference to the WinUI 3 NuGet package. 

For more on the Windows App SDK, see their [documentation](https://docs.microsoft.com/windows/apps/windows-app-sdk) and [repository](https://github.com/microsoft/WindowsAppSDK). For installation instructions, see  [Set up your development environment](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment). 
 
**NOTE**: The Windows App SDK was previously known by the code name Project Reunion. Some SDK assets may still use the code name, but these assets will be renamed in a future release. The term Project Reunion may also be used when referring to an existing asset or a specified earlier release.
 
## What's new
 
This release of WinUI 3 is focused on building towards new features for 1.0 Stable and fixing bugs. 

### New features
- Controls have been updated to reflect the latest Windows styles from [WinUI 2.6](https://docs.microsoft.com/en-us/windows/apps/winui/winui2/release-notes/winui-2.6#visual-style-updates)
- Single-project MSIX is supported. 
- WinUI package now targets 17763 and above, updated from 18362: [#921](https://github.com/microsoft/WindowsAppSDK/issues/921)
-  In-app toolbar is supported. However, the in-app toolbar and existing Hot Reload/Live Visual Tree support require the upcoming Visual Studio 17.0 Preview 5 release, available later in October.
 
### Bug fixes
- WebView2Runtime text is now localized

### Stability
This release includes unstable APIs and does not support building production apps. If you'd like to use WinUI 3 to build a production app, feel free to continue using the latest [Windows App SDK 0.8 release](https://docs.microsoft.com/windows/apps/windows-app-sdk/stable-channel).
 

### Known Issues
For a list of all the known issues for this Windows App SDK 1.0 preview release, please see the [Windows App SDK release notes](https://aka.ms/windowsappsdk/1.0-preview-2-release-notes).
- PopUp does not support 'ShouldContrainToRootBounds="False"':#5958
- In Single-project MSIX, you cannot reference a custom user control from a class library. If you require this scenario, use multi-project solution that includes the Window Application Project instead: #6028
 
## Getting started 
First, you'll need to set up your dev environment with the appropriate technologies. See our documentation for installation instructions and more information on project types: 
 
**[Install the Windows App SDK](https://docs.microsoft.com/windows/apps/windows-app-sdk/set-up-your-development-environment)**
 
**[Create WinUI 3 Projects](https://docs.microsoft.com/windows/apps/winui/winui3/create-winui3-projects)**
 
While you're developing, check out the [API Reference documentation](https://docs.microsoft.com/windows/winui/api/).
 
Take a look at our walk-through docs:
 
- [Get started developing apps with WinUI 3](https://docs.microsoft.com/windows/apps/winui/winui3/get-started-winui3-for-desktop)
- [Build a basic WinUI 3 app for desktop](https://docs.microsoft.com/windows/apps/winui/winui3/desktop-build-basic-winui3-app)
 
You can also update your existing WinUI 3 app to use the new Windows App SDK 1.0 preview release using these instructions: [Update existing projects to the latest release of the Windows App SDK](https://docs.microsoft.com/windows/apps/project-reunion/update-existing-projects-to-the-latest-release).
 
We love feedback! We encourage you to file any bug, big or small, on our repo using [this template](https://github.com/microsoft/microsoft-ui-xaml/issues/new?assignees=&labels=&template=bug_report.md&title=). Knowing which issues and features are important and/or critical to our customers highly influences which ones we tackle. Even though we ship with the Windows App SDK, please continue to file WinUI-specific bugs on this repo.   
 
## Using WinUI 3 and the Windows App SDK with our ecosystem partners
 
This latest release is in the process of being integrated into several other important ecosystem technologies. To test out and follow that progress, check out some of our partner technologies below (note that some of these technologies may not yet be available for Windows App SDK 1.0 preview):
 
- [Actipro Software](https://www.actiprosoftware.com) is migrating their vast UI control offerings over to WinUI 3, including their SyntaxEditor code editor, propertygrid, native type edit boxes, docking/MDI, charts, and more.
 
- [DevExpress](https://www.devexpress.com/winui/): DevExpress has released 20 new WinUI controls with Windows App SDK 0.8 support, including the Data Grid, Scheduler, Charts, Ribbon Toolbar, and more. All 20 UI components are available free-of-charge.
 
- Esri: [ArcGIS Runtime SDK for .NET]( https://developers.arcgis.com/net/) adds mapping, spatial analytics, and location intelligence capabilities to your apps on Android, iOS, and Windows. Support for WinUI 3 is [now available]( https://links.esri.com/arcgis-runtime-dotnet-sdk-winui-blog).
 
- [GrapeCity](https://www.grapecity.com/): [The ComponentOne WinUI controls](https://www.grapecity.com/componentone/winui-controls/?utm_source=Microsoft_GitHub&utm_medium=Dynamic&utm_campaign=Updated-WinUI-description_08/12/21) support modern desktop apps (Win32) and include calendar, accordion, input and our fast and flexible datagrid, FlexGrid.
 
- [Infragistics](https://www.infragistics.com/products/winui): Ultimate UI for WinUI brings business critical, high performing, and feature rich line of business controls to your apps that target any platform that runs Windows (including Windows on ARM64).
 
- [Syncfusion](https://www.syncfusion.com/winui-controls): Updated their projects to Microsoft.ProjectReunion from Microsoft.WinUI following upgrade instructions. All their controls are working fine.
 
- [Telerik UI for WinUI](https://www.telerik.com/winui): the market first UI controls suite for crafting Win32 and UWP apps with WinUI 3, comes with feature-rich controls like Ribbon, DataGrid, Charts, Gauges, Barcode, and more.
 
- [Uno Platform](https://github.com/unoplatform): Use WinUI 3 – Windows App SDK 0.8, XAML and C# to build pixel-perfect, single-codebase, native applications that can run on Web, Desktop and Mobile. It is free, open-source and available today.
 
- [Windows Community Toolkit (Microsoft)](https://aka.ms/wct-winui3): The WCT is currently working on supporting Windows App SDK 0.8 RC. It provides tons of new controls and capabilities for use in your WinUI app. You can check out their open source repo [here](https://aka.ms/windowstoolkit).
 
## What's next
To keep up with progress being made on WinUI 3, please see our [feature roadmap](https://aka.ms/winui3/feature-roadmap) which gets updated regularly. We also give monthly updates on our WinUI Community Calls, where you can directly ask the team any questions you have.

**Comment by JPTGamesAndApps** [comment]
Yay! Finally!! 
``Controls have been updated to reflect the latest Windows styles from WinUI 2.6``

**Comment by ghost1372** [comment]
> I'm trying to upgrade my existing app (which uses ProjectReunion 0.8.3) to the WAS 1.0 preview2, from the link to upgrade instructions given above I cannot find how to upgrade a single packaged project, I tried to follow the instructions but it results in a compilation error says that "A project cannot have more than one ApplicationXaml item". Through the issues list I noticed a similar one from #5906. However I've confirmed that there are no duplicate PackageReference entries in my `.csproj` file. I'll attach it below to provide useful information
> 
> My project's '.csproj' file: https://github.com/Pixeval/Pixeval/blob/master/src/Pixeval/Pixeval.csproj

You can not upgrade right now! Because you have used the community toolkit
`CommunityToolkit.WinUI.UI`
They have not updated the community yet
https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4171#issuecomment-937210970

**Comment by kmgallahan** [comment]
Strictly following the [instructions to Modify an existing project](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/single-project-msix?tabs=csharp#modify-an-existing-project) to "Package your app using single-project MSIX" results in the following error:

![Screenshot 2021-10-07 190128](https://user-images.githubusercontent.com/5379488/136473950-b47cb202-b479-4daa-a26e-ee3c00e621ba.jpg)

I resolved the problem by manually editing the `Package.appxmanifest` file to more closely match one created using the latest project template, and moving/renaming files/folders.

**Comment by shelllet** [comment]
i spent a lot of time to test , may be when i remove tabview and TeachingTip. the ui can display. so i had to rollback to 1.0-preview1

**Comment by jtorjo** [comment]
Since `MediaPlayerElement` controls won't make it this year... I have 2 questions:

(I assume `MediaComposition` is already ported)

1. Does `composition.RenderToFileAsync` work at this time?
2. Does `MediaClip.CreateFromFileAsync` work? 

In other words, inserting a video into a composition, and then later on rendering it into a video.

**Comment by hez2010** [comment]
Has mica been added to WinUI 3? I still cannot use it.

**Comment by seven-mile** [comment]
> Has mica been added to WinUI 3? I still cannot use it.

Nope. Mica is something like out-of-app Acrylic. It uses OS-associated CompositionSource from the wallpaper, which cannot be done with WinUI3 Composition. So It won't be released until the full Acrylic is completed I guess.

But I had checked the 1.0preview2 doc before and found [Microsoft.UI.Composition.SystemBackdrops](https://docs.microsoft.com/zh-cn/windows/winui/api/microsoft.ui.composition.systembackdrops?view=winui-3.0-preview) namespace, which contains runtimeclasses like DesktopAcrylicController and MicaController.

The `SetTarget` method of the both controllers requires an argument typed `Windows.Composition.CompositionTarget` which doesn't belong to WinUI3 Composition Engine. The so called "Win32 Example" hardly provides information. I'm not sure if we can use them by some interop.

To be optimistic, I presume mica is already under internal testing and will be out in the next release. @gabbybilka Would you be so kind to provide more information of the progress of mica, Gabby?

**Comment by iotjack** [comment]
when would WinUI support .net 6?

**Comment by dotMorten** [comment]
@iotjack it already does.

**Comment by iotjack** [comment]
any instructions for that? I use VS 2022 Preview 5.  When I tried to set Target framework to .NET 6.0, I got 
"Package Microsoft.ProjectReunion.InteractiveExperiences 0.8.5 is not compatible with net6.0"

**Comment by jrovny** [comment]
> > I'm trying to upgrade my existing app (which uses ProjectReunion 0.8.3) to the WAS 1.0 preview2, from the link to upgrade instructions given above I cannot find how to upgrade a single packaged project, I tried to follow the instructions but it results in a compilation error says that "A project cannot have more than one ApplicationXaml item". Through the issues list I noticed a similar one from #5906. However I've confirmed that there are no duplicate PackageReference entries in my `.csproj` file. I'll attach it below to provide useful information
> > My project's '.csproj' file: https://github.com/Pixeval/Pixeval/blob/master/src/Pixeval/Pixeval.csproj
> 
> You can not upgrade right now! Because you have used the community toolkit `CommunityToolkit.WinUI.UI` They have not updated the community yet [CommunityToolkit/WindowsCommunityToolkit#4171 (comment)](https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4171#issuecomment-937210970)

Can confirm. Removing the reference to "CommunityToolkit.WinUI.UI.Controls.DataGrid" Version="7.0.3" resolved the "A project cannot have more than one ApplicationXaml item" issue for me.

**Comment by gabbybilka** [comment]
Check out #6172 to see features from this release in Windows App SDK 1.0.
