### ISSUE TITLE
WinUI fails to compile on VS2019-16.4.0

### ISSUE THREAD

**Issue by mayankkrjain** [microsoft/microsoft-ui-xaml#1653]
**WinUI fails to compile on VS2019-16.4.0 (Preview 5.0)**

**Steps to reproduce the bug**

1. Install VS2019 Preview from https://visualstudio.microsoft.com/vs/preview/
2. Build the solution with following configuration - x64, Debug

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2019 Update (18362)            | Yes  |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |

**Error**
`>C:\Users\labuser\Documents\Microsoft\microsoft-ui-xaml\dev\inc\tracker_ref.h(366,79): error C3861: 'SharedHelpers': identifier not found (compiling source file C:\Users\labuser\Documents\Microsoft\microsoft-ui-xaml\dev\TestHooks\MUXControlsTestHooksLoggingMessageEventArgs.cpp)
`

**Comment by mdtauk** [comment]
I have been unable to compile and build the solution for about a month now.
Says Microsoft.UI.Xaml cannot be referenced, and a load of errors which may be resulting from that warning.

**Comment by kmahone** [comment]
@mayankkrjain do you also hit this problem with the release version of VS 2019? Or is this issue specific to the Preview 5 version?

**Comment by mdtauk** [comment]
> @mayankkrjain do you also hit this problem with the release version of VS 2019? Or is this issue specific to the Preview 5 version?

I am only running the preview version of VS 2019, with VS 2017.  I will try on release

**Comment by mdtauk** [comment]
> > @mayankkrjain do you also hit this problem with the release version of VS 2019? Or is this issue specific to the Preview 5 version?
> 
> I am only running the preview version of VS 2019, with VS 2017. I will try in the release version.

It works in the release version, but not in at least the past 3 Visual Studio 2019 previews

**Comment by ad1Dima** [comment]
Have same error on 16.4.2. 
Found strange additional error:
```
#if defined(_CPPRTTI) && !_HAS_STATIC_RTTI
#error /GR implies _HAS_STATIC_RTTI.
#endif // defined(_CPPRTTI) && !_HAS_STATIC_RTTI
```

_CPPRTTI is defined although /GR- option is selected for Microsoft.UI.Xaml project. 
Seems there is bug in MSVC...

**Comment by jevansaks** [comment]
I fixed this in master with #1716 . I don't see any other issues building in 16.4 or 16.5 preview.

**Comment by ad1Dima** [comment]
Ok.
I properly merged from master. Manually clear BuildOutput folder and everything compiles now.
