### ISSUE TITLE
[1.0 - preview3] App does not contain a definition for 'InitializeComponent' in the constructor of App.xaml.cs

### ISSUE THREAD

**Issue by KusiTec** [microsoft/microsoft-ui-xaml#6209]
After upgrading from projectreunion 0.8 to 1.0 - preview3, arises the error CS1061:

- 'App' does not contain a definition for 'InitializeComponent' and no accessible extension method 'InitializeComponent' accepting a first argument of type 'App' could be found (are you missing a using directive or an assembly reference?)
- It should be noted here that the class name (x:Class="KusiTec.Kodis.WinUi.App") in the App.xaml is red underlined, with the message, the the class is already declared.

During cleaning the solution, arises the warning MSB4011:

- C:\Users\KusiT\.nuget\packages\microsoft.projectreunion.winui\0.8.0\buildTransitive\Microsoft.WinUI.props(24,3): warning MSB4011: "C:\Users\KusiT\.nuget\packages\microsoft.windowsappsdk\1.0.0-preview3\build\Microsoft.UI.Xaml.Markup.Compiler.props" cannot be imported again. It was already imported at "C:\Users\KusiT\.nuget\packages\microsoft.windowsappsdk\1.0.0-preview3\build\Microsoft.WinUI.props (25,3)". This is most likely a build authoring error. This subsequent import will be ignored. [C:\Users\KusiT\source\repos\KusiTec\KusiTec.Kodis.WinUi\KusiTec.Kodis.WinUi\KusiTec.Kodis.WinUi.csproj]

All projectrenunion packages are unistalled. it seems, that the dotnet sdk 5.0.402 takes access to the package 'projectreunion.winui'. A corresponding error occurs, if this nuget package is not accessible.

Everything worked fine before the upgrade! Thanks for help.

Environment:
- VS 19 / 16.11.5
- Target framework: net5.0-windows10.0.19041.0
- target platform min version: 10.0.19041.0

**Comment by StephenLPeters** [comment]
@MikeHillberg and @evelynwu-msft FYI
