### ISSUE TITLE
Question: Writing unit tests for WinUI 3 libraries

### ISSUE THREAD

**Issue by chingucoding** [microsoft/microsoft-ui-xaml#6279]
I've tried following this article https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/ however I wasn't able to make this work using the 1.0.0 previews. Is this expected? What is the current way to write unit tests for WinUI 3 class libraries?

**Comment by Zachael** [comment]
error CS7069: Reference to type 'DispatcherQueue' claims it is defined in 'Microsoft.WinUI', but it could not be found

https://github.com/microsoft/testfx/issues/993

**Comment by chingucoding** [comment]
Even if you omit that line (and break UI tests), the app doesn't seem to work properly. It sometimes starts and doesn't execute tests, sometimes the test run fails with the error message that the app already is running.

**Comment by StephenLPeters** [comment]
@chigy about the bug in the documentation app.

**Comment by MarkBrainfire** [comment]
So ... is there a way to write unit tests for WinUI3 Desktop Class Libraries yet???

**Comment by aborlaza-gpsw** [comment]
Still happening for Winui3 libraries.
I tried what was in  https://devblogs.microsoft.com/ifdef-windows/winui-desktop-unit-tests/ - did not work, unit tests in test exploer just result to Test Not Run.
I tried creating a Winui class library, then edited the things in the link above as adding the mstests references and the csproj change - still did not work, results showing Test Not Run
I tried creating a Winui class library using NUnit dll - did not work, same thing.

**Comment by michael-hawker** [comment]
We've been using MSTest to test Windows App SDK parts for the Windows Community Toolkit and for our new infrastructure [Toolkit Labs](https://github.com/CommunityToolkit/Labs-Windows) since last year. I just don't think there's a proper default project template in VS? Maybe that's the root of the issue here?

We've hand-crafted a lot of our infrastructure copying things over from UWP prior Windows App SDK work we've done in initial migrations of the Windows Community Toolkit (which we're now having trouble building again).

There were definitely issues post 1.0 which required updates now available in 1.2 and later MSTest packages (2.2.10); in addition to some Windows Server 2022 OS patches (if you were deploying to that OS in a GitHub CI VM).

**Comment by chingucoding** [comment]
Yes @michael-hawker this is mostly about not having a dedicated testing projec template. I wrote my own ones because I was too lazy to follow the steps every time however having something "official" in that area would make it a lot cleared. Especially since it shows that this is indeed supported.

**Comment by DarkKnight1302** [comment]
I am able to execute Unit tests in WinUI 3 application
Csproj: 
`<PackageReference Include="FluentAssertions" Version="5.10.3" />
   <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.3" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230217.4" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />
    <PackageReference Include="Moq" Version="4.14.5" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
    <PackageReference Include="MSTest.TestFramework" Version="2.2.8" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.analyzers" Version="1.1.0" />
    <PackageReference Include="xunit.runner.console" Version="2.4.2">`

In App.xaml.cs

`
            Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.CreateDefaultUI();
            m_window = new MainWindow();

            m_window.Activate();
            UITestMethodAttribute.DispatcherQueue = m_window.DispatcherQueue;

            Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run(Environment.CommandLine);`

**Comment by Brubning** [comment]
@DarkKnight1302 are your unit tests in the same project as the application? I'm struggling to get this going with a separate test project that references a WinUi application project.

@MarkBrainfire did you work out an approach to unit testing with a WinUi class library?

**Comment by Brubning** [comment]
I've spent the afternoon going through different configurations to get unit testing up and running.

I've just come off WPF and Avalonia projects where the unit test project references the application project directly, it appears that Win UI won't let you do that. If you try to reference the application project (output type of WinExe) from a unit test project (also WinExe)  you will see lots of errors like `APPX1101: Payload contains two or more files with the same destination path 'resources.pri'` on build.

I did a quick sample project to show the failing configuration. It's in GitHub (https://github.com/Brubning/WinUi.UnitTestExperiment). Look at the [WinUi.UnitTestExperiment.AppUi.sln](https://github.com/Brubning/WinUi.UnitTestExperiment/blob/main/WinUi.UnitTestExperiment.AppUi/WinUi.UnitTestExperiment.AppUi.sln).

Instead, I had to move my view models, commands etc. to a Class Library project and reference _that_ from the unit test project. I could then add a Win UI application project alongside which references the same class library. This means the application becomes really lightweight, it really only contains configuration, DI etc. and nothing that qualifies for unit test coverage. Really it's just a deployment container (Which is good for MVVM).

Again I did a quick sample to show this working. Look at the [WinUi.UnitTestExperiment.ClassLibrary.sln](https://github.com/Brubning/WinUi.UnitTestExperiment/blob/main/WinUi.UnitTestExperiment.ClassLibrary/WinUi.UnitTestExperiment.ClassLibrary.sln).

My unit test project configuration started out from the VS Extension provided by @chingucoding (See https://github.com/microsoft/microsoft-ui-xaml/issues/6258) but I upgraded to current versions for MSTest, WinUI and Windows App SDK.

One other thing, despite what the [documentation](https://learn.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=cs-vs-professional%2Ccpp-vs-professional%2Cvs-2022-17-1-a%2Cvs-2022-17-1-b) says, you also need the UWP workload installed in Visual Studio for the test runner to work. 

Not sure if any of that is helpful. Thought I'd share my findings, most of it is obvious unless you don't know. I'm not 100% sure that I've taken the right approach, please feel free to point out where I'm going wrong.

**Comment by terrycox** [comment]
As near as I can tell, you can roll your own. That way we can have a hundred different versions of an MSTest configuration, working (or not) a hundred different ways. Where the heck is Microsoft on this? (Or a companion question: Who in Microsoft answers this? As witness adding this to the mix:    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.7.2" />.)

**Comment by evelynwu-msft** [comment]
https://github.com/microsoft/WindowsAppSDK/pull/3942 added Unit Test project templates for WinAppSDK to the VSIX which will ship as part of the upcoming 1.5 release.

**Comment by zimchild** [comment]
> I am able to execute Unit tests in WinUI 3 application Csproj:
> 
> `
> 
> ```
> <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.2.230217.4" />
> 
> <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.755" />
> 
> <PackageReference Include="Moq" Version="4.14.5" />
> 
> <PackageReference Include="MSTest.TestAdapter" Version="2.2.8" />
> 
> <PackageReference Include="MSTest.TestFramework" Version="2.2.8" />
> 
> <PackageReference Include="xunit" Version="2.4.2" />
> 
> <PackageReference Include="xunit.analyzers" Version="1.1.0" />
> 
> <PackageReference Include="xunit.runner.console" Version="2.4.2">`
> ```
> 
> In `<PropertyGroup>` csproj also add
> 
> `<GenerateProgramFile>false</GenerateProgramFile>`
> 
> In App.xaml.cs
> 
> ```
>       `  Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.CreateDefaultUI();
>         m_window = new MainWindow();
>         m_window.Activate();
>         UITestMethodAttribute.DispatcherQueue = m_window.DispatcherQueue;
> 
>         Microsoft.VisualStudio.TestPlatform.TestExecutor.UnitTestClient.Run(Environment.CommandLine);`
> ```

Thank you, this worked for me.

**Comment by AlexanderBlackman** [comment]
> I am able to execute Unit tests in WinUI 3 application

How did you execute the tests?  Using your method,  the tests are found in VS's test explorer, but don't execute.
In Test Runner, I get the following message.
```
No test is available in C:\Users\Alex\source\repos\RezSlice\RezSlice.UI\bin\x64\Debug\net8.0-windows10.0.22621.0\RezSlice.UI.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
No tests found for the current filter in the assembly C:\Users\Alex\source\repos\RezSlice\RezSlice.UI\bin\x64\Debug\net8.0-windows10.0.22621.0\RezSlice.UI.dll
No test is available in C:\Users\Alex\source\repos\RezSlice\RezSlice.UI\bin\x64\Debug\net8.0-windows10.0.22621.0\RezSlice.UI.dll. Make sure that test discoverer & executors are registered and platform & framework version settings are appropriate and try again.
No tests found for the current filter in the assembly C:\Users\Alex\source\repos\RezSlice\RezSlice.UI\bin\x64\Debug\net8.0-windows10.0.22621.0\RezSlice.UI.dll
 Summary: Passed: 0, Failed: 0, Ignored: 0
Duration: 1.21 seconds

```

Also, I needed to install Microsoft.TestPlatform.TestHost to get it to build.
