### ISSUE TITLE
 [1.1 Preview 2] The `Connect` function in the file `xaml.g.hpp` cannot be called .

### ISSUE THREAD

**Issue by shelllet** [microsoft/microsoft-ui-xaml#6999]
### Describe the bug

Correct stack trace:
![image](https://user-images.githubusercontent.com/16729017/164132480-96fe4b02-ef69-4a5e-a1a2-ce528f2f16c5.png)

but when:
```
unsealed runtimeclass GraphicsItem : Microsoft.UI.Xaml.Controls.ContentControl{}

[default_interface]
runtimeclass HeadItem : GraphicsItem
{
}
```
MyHit control:
```
<Ellipse x:Name="MyHit" Fill="White"
                Height="6"
                Width="6" 
                 Tag="{x:Bind local:HitType.Exit1}"
                RelativePanel.AlignBottomWithPanel="True" RelativePanel.AlignHorizontalCenterWithPanel="True">
```

```
HeadItem()
{
  InitializeComponent();
  
  MyHit().SetValue(GraphicsItem::OwnerProperty(), *this); // crash here, because MyHit() return null.
}

```

Why MyHit() is return null, becuase the function `Connect` cannot be called.

```
 template <typename D, typename ... I>
    void HeadItemT<D, I...>::Connect(int32_t connectionId, IInspectable const& target)
    {
        switch (connectionId)
        {
        case 2:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Shapes::Ellipse>();
                this->MyEllipse(targetElement);
            }
            break;
        case 3:
            {
                auto targetElement = target.as<::winrt::Microsoft::UI::Xaml::Shapes::Ellipse>();
                this->MyHit(targetElement);
            }
            break;
        }
        _contentLoaded = true;
    }
```

### Steps to reproduce the bug

1. Create the flowing code:
````
      unsealed runtimeclass GraphicsItem : Microsoft.UI.Xaml.Controls.ContentControl{}
      
      [default_interface]
      runtimeclass HeadItem : GraphicsItem
      {
      }
````
2. Add `winui` Compoent in the `HeadItem.xaml`
3.  Set the Component Name
4.  Get the Component after the `InitializeComponent`

### NuGet package version

WinUI 3 - Windows App SDK 1.0

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

**Comment by shelllet** [comment]
there is no fixed in 1.1 stable. my app can't run when upgrade to 1.1 stable version.

**Comment by shelllet** [comment]
I found why, because i exclude 'GraphicsItem' and remove `GraphicsItem.xaml`,  and include the `GraphicsItem` .the `.vcxproj` will miss the 'DependentUpon' for `GraphicsItem`.
so `Connection` can't work, this is just shit.

i upload simple source code , you go to see it.

repo:https://github.com/shelllet/WinUIDependentUpon/tree/master

and if i exclude the `GraphicsItem` and reinclude, there will be appear 'unresolved external symbol ....' as follows.


![image](https://user-images.githubusercontent.com/16729017/174433052-fb1de409-9ef0-482e-96ca-0f0ed232bb33.png)
